### ISSUE TITLE
Full version of the data

### ISSUE THREAD

**Issue by IreneZihuiLi** [echen102/COVID-19-TweetIDs#1]
Hi,

Is it possible to release the texts instead of the TweetIDs? I think I still need APIs to download/extract the original tweets from the web.

Thanks.

**Comment by echen102** [comment]
Hi! 

Unfortunately, we aren't able to publicly release the text from the Tweets that we've collected (as per Twitter's Developer's [Terms of Service](https://developer.twitter.com/en/developer-terms/agreement-and-policy) - see the "content redistribution" section). 

However, it's fairly simple to rehydrate the TweetIDs so that you have the full text, as [Hydrator](https://github.com/DocNow/hydrator) provides a very intuitive GUI that manages your Twitter rate limit for you, and returns a JSON file (and can also generate a CSV file) with all of the Tweets. You'll need to [apply](https://developer.twitter.com/en/apply-for-access) for a Twitter Developer account to generate your own access tokens, but beyond that you shouldn't need to code anything to extract the original tweets.

**Comment by echen102** [comment]
Hi,

@edsu has just added a script that will help you hydrate the tweets from command line. I'll be adding instructions to use his script in our README. 

I hope you're not running into too many issues hydrating the tweet-ids - I'm going to close this issue, but please feel free to reach out to me if you are!
