### ISSUE TITLE
Multi-language result

### ISSUE THREAD

**Issue by binghesam** [echen102/COVID-19-TweetIDs#18]
Hi all. Thanks for your effort. In you paper, you mention that you use the English-related keyword for the search. But, in the result, you show that there are Janpanese tweets? It is really strange. Can you explain for this reason. And also, show the sample ids in your data. Many thanks. I am quite confused about the multi-language result. Many thanks.

**Comment by echen102** [comment]
Hi! We tracked English keywords, but these keywords could be anywhere in the Tweet's raw json payload, and we didn't specifically filter for any language. This means that, if a tweet that is classified as Japanese happens to contain one of the keywords that we're tracking, we'll collect that particular tweet. Because we did track English keywords, the majority of our tweets are in English, but quite a few of the keywords we tracked (e.g. coronavirus) are used across cultures, thus resulting in us having a diverse representation of different languages.
