### ISSUE TITLE
new data

### ISSUE THREAD

**Issue by kbathina** [echen102/COVID-19-TweetIDs#3]
Do you have a general time period/rate of when new tweet ids will be released?

**Comment by echen102** [comment]
Hi! 
I'm hoping to have a few more weeks uploaded in the next few hours, and then the rest such that the data will be up until 3/12 hopefully by EOD today or, at the latest, tomorrow. I'm currently playing a bit of catch up to process all the Tweets that have been collected thus far (patching in some missing data, dropping duplicates).

As for the general schedule for releases, once this repo has caught up, it'll hopefully be on a weekly basis. This may change as we determine how best to get the Tweet IDs uploaded efficiently and quickly, as we understand that Tweets will take a while to hydrate.

**Comment by kbathina** [comment]
Will current tweet text files be updated with new information or will new tweets always be in new files?

**Comment by echen102** [comment]
New Tweets will almost always be in new files -- there may be the odd case where one file may change as we add new Tweets since we're keeping Tweets grouped by hour, but this shouldn't happen too often if at all (I am actively trying to avoid this and will make a note in the commit notes if there are files that were modified).

**Comment by kbathina** [comment]
Thank you! I have no further questions, so you can close this issue
