### ISSUE TITLE
twarc issue

### ISSUE THREAD

**Issue by kbathina** [echen102/COVID-19-TweetIDs#4]
This could just be an issue on my side, but 
```
twarc configure
```
did not work on my system, Instead, I just added it to the python script directly.

**Comment by echen102** [comment]
Hi @kbathina , did you check to see that twarc was installed properly ? (e.g., when you type in the command `twarc` , you should see something like: 

`usage: twarc [-h] [--log LOG] [--consumer_key CONSUMER_KEY]
             [--consumer_secret CONSUMER_SECRET] [--access_token ACCESS_TOKEN]
             [--access_token_secret ACCESS_TOKEN_SECRET] [--config CONFIG]
             [--profile PROFILE] [--warnings]
             [--connection_errors CONNECTION_ERRORS]
             [--http_errors HTTP_ERRORS] [--max_id MAX_ID]
             [--since_id SINCE_ID] [--result_type {mixed,recent,popular}]
             [--lang LANG] [--geocode GEOCODE] [--locations LOCATIONS]
             [--follow FOLLOW] [--recursive] [--tweet_mode {compat,extended}]
             [--protected] [--output OUTPUT] [--format {json,csv,csv-excel}]
             [--split SPLIT] [--skip_key_validation]
             {configure,dehydrate,filter,followers,friends,help,hydrate,replies,retweets,sample,search,timeline,trends,tweet,users,listmembers,version}
             [query]
twarc: error: the following arguments are required: command`

My suspicion is that this is an issue with your setup, though I can't say much because I don't know what error you're receiving or what your setup looks like.

**Comment by kbathina** [comment]
You are most likely correct. I can't isolate the error yet. It might be useful to say that this can be done directly in python in the README

**Comment by echen102** [comment]
Thanks for the suggestion! I've made a note of this in the latest README
